// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriAloMf2vgRtqMX43SlwjIliw0Q3JriA',
    appId: '1:2996449144:web:e8921b6a29fccb4e7da28d',
    messagingSenderId: '2996449144',
    projectId: 'parlormanagement',
    authDomain: 'parlormanagement.firebaseapp.com',
    storageBucket: 'parlormanagement.firebasestorage.app',
    measurementId: 'G-GLL67SRRQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvL9OVg0yA6QOzVlsUoWOeueeWyAK4nII',
    appId: '1:2996449144:android:85a66a212d4a551b7da28d',
    messagingSenderId: '2996449144',
    projectId: 'parlormanagement',
    storageBucket: 'parlormanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxosaQvRpbE4hkqDJ2gmWdD3g8sHpiShQ',
    appId: '1:2996449144:ios:461640d6dc68505e7da28d',
    messagingSenderId: '2996449144',
    projectId: 'parlormanagement',
    storageBucket: 'parlormanagement.firebasestorage.app',
    iosBundleId: 'com.maans.parlormanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxosaQvRpbE4hkqDJ2gmWdD3g8sHpiShQ',
    appId: '1:2996449144:ios:461640d6dc68505e7da28d',
    messagingSenderId: '2996449144',
    projectId: 'parlormanagement',
    storageBucket: 'parlormanagement.firebasestorage.app',
    iosBundleId: 'com.maans.parlormanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDriAloMf2vgRtqMX43SlwjIliw0Q3JriA',
    appId: '1:2996449144:web:30379c29b813f2197da28d',
    messagingSenderId: '2996449144',
    projectId: 'parlormanagement',
    authDomain: 'parlormanagement.firebaseapp.com',
    storageBucket: 'parlormanagement.firebasestorage.app',
    measurementId: 'G-MQ7W08GFE9',
  );
}
